package ws18.model;

public enum EventType {
    //Reporting
    RETRIEVE_CUSTOMER_REPORTS,
    RETRIEVE_MERCHANT_REPORTS,
    REQUEST_TRANSACTIONS_RESPONSE,
    REQUEST_TRANSACTIONS_SUCCEED
}